# CMake generated Testfile for 
# Source directory: /home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp
# Build directory: /home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/debug/popf/testcases/lpsameasstp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pipesnt-11-can-be-solved-test-scheduling "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-I" "-D" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-11.pddl")
add_test(pipesnt-11-can-be-solved-cplex "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2-cplex" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-11.pddl")
add_test(pipesnt-11-can-be-solved-clp "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2-clp" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-11.pddl")
add_test(pipesnt-11-can-be-solved-stp "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-I" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-11.pddl")
add_test(pipesnt-12-can-be-solved-test-scheduling "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-I" "-D" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
add_test(pipesnt-12-can-be-solved-cplex "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2-cplex" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
add_test(pipesnt-12-can-be-solved-clp "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2-clp" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
add_test(pipesnt-12-can-be-solved-stp "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-I" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
add_test(pipesnt-21-can-be-solved-test-scheduling "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-I" "-D" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
add_test(pipesnt-21-can-be-solved-cplex "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2-cplex" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
add_test(pipesnt-21-can-be-solved-clp "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2-clp" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
add_test(pipesnt-21-can-be-solved-stp "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-I" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
add_test(matchlift-02-can-be-solved-test-scheduling "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-I" "-D" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/matchlift-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/matchlift-problem-02.pddl")
