# CMake generated Testfile for 
# Source directory: /home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp
# Build directory: /home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/debug/popf/testcases/lpsameasstp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pipesnt-11-can-be-solved-test-scheduling "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-I" "-D" "-T" "-v1" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-11.pddl")
set_tests_properties(pipesnt-11-can-be-solved-test-scheduling PROPERTIES  _BACKTRACE_TRIPLES "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;1;add_test;/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;0;")
add_test(pipesnt-11-can-be-solved-cplex "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2-cplex" "-T" "-v1" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-11.pddl")
set_tests_properties(pipesnt-11-can-be-solved-cplex PROPERTIES  _BACKTRACE_TRIPLES "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;2;add_test;/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;0;")
add_test(pipesnt-11-can-be-solved-clp "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2-clp" "-T" "-v1" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-11.pddl")
set_tests_properties(pipesnt-11-can-be-solved-clp PROPERTIES  _BACKTRACE_TRIPLES "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;3;add_test;/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;0;")
add_test(pipesnt-11-can-be-solved-stp "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-I" "-T" "-v1" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-11.pddl")
set_tests_properties(pipesnt-11-can-be-solved-stp PROPERTIES  _BACKTRACE_TRIPLES "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;4;add_test;/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;0;")
add_test(pipesnt-12-can-be-solved-test-scheduling "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-I" "-D" "-T" "-v1" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
set_tests_properties(pipesnt-12-can-be-solved-test-scheduling PROPERTIES  _BACKTRACE_TRIPLES "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;6;add_test;/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;0;")
add_test(pipesnt-12-can-be-solved-cplex "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2-cplex" "-T" "-v1" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
set_tests_properties(pipesnt-12-can-be-solved-cplex PROPERTIES  _BACKTRACE_TRIPLES "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;7;add_test;/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;0;")
add_test(pipesnt-12-can-be-solved-clp "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2-clp" "-T" "-v1" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
set_tests_properties(pipesnt-12-can-be-solved-clp PROPERTIES  _BACKTRACE_TRIPLES "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;8;add_test;/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;0;")
add_test(pipesnt-12-can-be-solved-stp "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-I" "-T" "-v1" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
set_tests_properties(pipesnt-12-can-be-solved-stp PROPERTIES  _BACKTRACE_TRIPLES "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;9;add_test;/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;0;")
add_test(pipesnt-21-can-be-solved-test-scheduling "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-I" "-D" "-T" "-v1" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
set_tests_properties(pipesnt-21-can-be-solved-test-scheduling PROPERTIES  _BACKTRACE_TRIPLES "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;11;add_test;/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;0;")
add_test(pipesnt-21-can-be-solved-cplex "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2-cplex" "-T" "-v1" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
set_tests_properties(pipesnt-21-can-be-solved-cplex PROPERTIES  _BACKTRACE_TRIPLES "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;12;add_test;/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;0;")
add_test(pipesnt-21-can-be-solved-clp "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2-clp" "-T" "-v1" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
set_tests_properties(pipesnt-21-can-be-solved-clp PROPERTIES  _BACKTRACE_TRIPLES "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;13;add_test;/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;0;")
add_test(pipesnt-21-can-be-solved-stp "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-I" "-T" "-v1" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-domain.pddl" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/pipesnt-problem-12.pddl")
set_tests_properties(pipesnt-21-can-be-solved-stp PROPERTIES  _BACKTRACE_TRIPLES "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;14;add_test;/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;0;")
add_test(matchlift-02-can-be-solved-test-scheduling "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-I" "-D" "-T" "-v1" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/matchlift-domain.pddl" "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/matchlift-problem-02.pddl")
set_tests_properties(matchlift-02-can-be-solved-test-scheduling PROPERTIES  _BACKTRACE_TRIPLES "/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;17;add_test;/home/canfresco/Documents/AIRo2-ws/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/lpsameasstp/CMakeLists.txt;0;")
