(define (problem pt-03)
; Test case provided by Ashutosh Verma (avermaa at gmail dot com)
 (:domain t3)
 (:init (not-started) (= utime 0) (= endtime 0) (= total-duration 150) )
 (:goal (six-done))
)
