# CMake generated Testfile for 
# Source directory: /home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/coordination
# Build directory: /home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/release/popf/testcases/coordination
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(driverlogshift1-can-be-solved "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/release/popf/popf2" "-I" "-D" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/coordination/driverlogshift-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/coordination/driverlogshift-problem-01.pddl")
add_test(driverlogshift2-plan-could-be-found "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/release/popf/popf2" "-r" "-s" "-I" "-D" "-v1" "-T" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/coordination/driverlogshift-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/coordination/driverlogshift-problem-02.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/coordination/driverlogshift-plan-02")
add_test(driverlogshift3-can-be-solved "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/release/popf/popf2" "-I" "-D" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/coordination/driverlogshift-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/coordination/driverlogshift-problem-03.pddl")
add_test(driverlogshift9-can-be-solved "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/release/popf/popf2" "-I" "-D" "-T" "-v1" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/coordination/driverlogshift-domain.pddl" "/home/ubuntu18/Desktop/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/coordination/driverlogshift-problem-09.pddl")
