(define (problem matchliftproblem01)
	(:domain matchlift)
(:objects
	fuse0 fuse1 fuse2 fuse3 fuse4 fuse5 fuse6 -fuse
match0 match1 match2 match3 match4 match5 match6 -match
		lift1 - lift
	floor1 floor2 - floor
	elec1 elec2 elec3 elec4 elec5 - electrician
		room1-1 room1-2 room1-3 room1-4 room1-5 room2-1 room2-2 room2-3 room2-4 room2-5 - room
)
(:init
	(fuseinroom fuse0 room1-3)
	(fuseinroom fuse1 room2-1)
	(fuseinroom fuse2 room1-2)
	(fuseinroom fuse3 room2-3)
	(fuseinroom fuse4 room1-5)
	(fuseinroom fuse5 room1-5)
	(fuseinroom fuse6 room2-2)
	(unused match0)
	(unused match1)
	(unused match2)
	(unused match3)
	(unused match4)
	(unused match5)
	(unused match6)
	(connectedfloors floor1 floor2)
	(connectedfloors floor2 floor1)
	(roomonfloor room1-1 floor1)
	(roomonfloor room1-2 floor1)
	(roomonfloor room1-3 floor1)
	(roomonfloor room1-4 floor1)
	(roomonfloor room1-5 floor1)
	(roomonfloor room2-1 floor2)
	(roomonfloor room2-2 floor2)
	(roomonfloor room2-3 floor2)
	(roomonfloor room2-4 floor2)
	(roomonfloor room2-5 floor2)
	(onfloor elec1 floor1)
	(handfree elec1)
	(onfloor elec2 floor1)
	(handfree elec2)
	(onfloor elec3 floor1)
	(handfree elec3)
	(onfloor elec4 floor2)
	(handfree elec4)
	(onfloor elec5 floor1)
	(handfree elec5)
	(liftonfloor lift1 floor2)
)
(:goal (and 
	(mended fuse0)
	(mended fuse1)
	(mended fuse2)
	(mended fuse3)
	(mended fuse4)
	(mended fuse5)
	(mended fuse6)
	)
)
)
