# CMake generated Testfile for 
# Source directory: /home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests
# Build directory: /home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/testcases/LPBFTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(airport-temporal-old-heuristic "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-I" "-c" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/airport-temporal-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/airport-temporal-problem.pddl")
add_test(airport-temporal-total-order "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-I" "-T" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/airport-temporal-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/airport-temporal-problem.pddl")
add_test(airport-temporal-old-heuristic-no-action-compression "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-I" "-k" "-c" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/airport-temporal-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/airport-temporal-problem.pddl")
add_test(airport-temporal-total-order-no-action-compression "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-T" "-I" "-k" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/airport-temporal-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/airport-temporal-problem.pddl")
add_test(driverlog-time-old-heuristic "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-I" "-c" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/driverlog-time-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/driverlog-time-problem.pddl")
add_test(driverlog-time-total-order "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-I" "-T" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/driverlog-time-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/driverlog-time-problem.pddl")
add_test(driverlog-time-old-heuristic-no-action-compression "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-I" "-k" "-c" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/driverlog-time-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/driverlog-time-problem.pddl")
add_test(driverlog-time-total-order-no-action-compression "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-T" "-I" "-k" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/driverlog-time-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/driverlog-time-problem.pddl")
add_test(rovers-time-old-heuristic "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-I" "-2" "-c" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/rovers-time-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/rovers-time-problem.pddl")
add_test(rovers-time-total-order "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-I" "-2" "-T" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/rovers-time-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/rovers-time-problem.pddl")
add_test(rovers-time-old-heuristic-no-action-compression "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-I" "-2" "-k" "-c" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/rovers-time-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/rovers-time-problem.pddl")
add_test(rovers-time-total-order-no-action-compression "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-T" "-2" "-I" "-k" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/rovers-time-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/rovers-time-problem.pddl")
add_test(satellite-complex-old-heuristic "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-I" "-c" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/satellite-complex-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/satellite-complex-problem.pddl")
add_test(satellite-complex-total-order "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-I" "-T" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/satellite-complex-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/satellite-complex-problem.pddl")
add_test(satellite-complex-old-heuristic-no-action-compression "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-I" "-k" "-c" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/satellite-complex-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/satellite-complex-problem.pddl")
add_test(satellite-complex-total-order-no-action-compression "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/debug/popf/popf2" "-D" "-T" "-I" "-k" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/satellite-complex-domain.pddl" "/home/ubuntu18/Documents/AIRo2-Assignment-2/popf-tif/planner/src/popf/testcases/LPBFTests/satellite-complex-problem.pddl")
