(define (problem pfile1)
    (:domain blocksworld)
    (:objects
	B0 B1 B2 B3 - block
	C0 C1 C2 - column
	)
    (:init
	(arm-empty)

	(= (weight-block B0) 5)
	(above B0 C0)
	(on-column B0)
	(clear B0)
	(= (weight-block B1) 9)
	(above B1 C1)
	(on-column B1)
	(= (weight-block B2) 7)
	(above B2 C2)
	(on-column B2)
	(clear B2)
	(= (weight-block B3) 2)
	(above B3 C1)
	(on B3 B1)
	(clear B3)
	(= (weight-column C0) 5)
	(= (maxheight C0) 10)
	(= (height-column C0) 9)
	(= (weight-column C1) 11)
	(= (maxheight C1) 10)
	(= (height-column C1) 9)
	(= (weight-column C2) 7)
	(= (maxheight C2) 10)
	(= (height-column C2) 9)
	)
    (:goal
	(and (on-column B0)
	    (on B1 B0)
	    (on-column B2)
	    (on B3 B1)
	    )
	)
)
