(define (problem run-generator2)
    (:domain generator)
    (:objects generator)
    (:init 	(= (fuel-level generator)  0)
		(= (capacity generator)  90)
		(not-refueling generator)
		(not-generating generator)
		(not-done-fill generator)
     )  
     (:goal (generator-ran))
) 
